# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for IIO SDRs
#

# When adding new entries keep the list in alphabetical order

obj-$(CONFIG_SKYNET_RX)			+= skynet_rx.o
obj-$(CONFIG_SKYNET_TX)			+= skynet_tx.o
obj-$(CONFIG_SKYNET_CLK)		+= skynet_clk.o